services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - rabbitmq_network

  commandapp:
    depends_on:
      - db-command
      - rabbitmq
    build:
      dockerfile: Dockerfile
      context: .
    image: command-docker
    container_name: CQRS
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      DB_NAME: ${DB_NAME}
      RABBITMQ_URL: ${RABBITMQ_URL}
    networks:
      - rabbitmq_network

  db-command:
    depends_on:
      - rabbitmq
    image: mongo
    container_name: mongo-commands
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: Command
    volumes:
      - ./mongo:/data/db
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
